/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package udream;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author User
 */
public class admin_home extends javax.swing.JPanel {

    /**
     * Creates new form admin_home
     */
    public admin_home() {
        initComponents();
      jLabel6.setSize(800,800);
        ImageIcon icon = new ImageIcon(getClass().getResource("admin_pic.png"));
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(jLabel6.getWidth(),jLabel6.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
       jLabel6.setIcon(scaledIcon);
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 350));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
