package udream;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class Bsc_Courses_Panel extends javax.swing.JPanel {

    public void init() {
        overview.setLineWrap(true);
        overview.setWrapStyleWord(true);
        application_pre_req.setLineWrap(true);
        application_pre_req.setWrapStyleWord(true);
        ACT = false;
        SAT = false;
        ILETS = false;
        TOFEL = false;
        PTE = false;
        jLabel14.setVisible(false);
        Ilets_score.setVisible(false);
        jLabel15.setVisible(false);
        jLabel33.setVisible(false);
        jLabel18.setVisible(false);
        jLabel28.setVisible(false);
        sat_total_score.setVisible(false);
        jLabel21.setVisible(false);
        jLabel22.setVisible(false);
        jLabel23.setVisible(false);
        jLabel26.setVisible(false);
        jLabel25.setVisible(false);
        jLabel27.setVisible(false);
        jLabel24.setVisible(false);
        jLabel11.setVisible(false);
        jLabel12.setVisible(false);
        sat_math_score.setVisible(false);
        sat_rw_score.setVisible(false);
        pte_score.setVisible(false);

        tofel_score.setVisible(false);
        act_score.setVisible(false);
        jLabel37.setVisible(false);
        gre_verbal.setVisible(false);
        jLabel38.setVisible(false);
        gre_quants.setVisible(false);
        jLabel39.setVisible(false);
        gre_awa.setVisible(false);
        jLabel36.setVisible(false);
        gre_total.setVisible(false);
        jLabel35.setVisible(false);
        gmat_score.setVisible(false);
        jLabel10.setVisible(false);
        jLabel13.setVisible(false);
        jLabel34.setVisible(false);
        jLabel40.setVisible(false);
        jRadioButton1.setVisible(false);
        jRadioButton3.setVisible(false);
        jRadioButton12.setVisible(false);
        jRadioButton13.setVisible(false);
         jRadioButton2.setVisible(false);
        jRadioButton4.setVisible(false);
        jRadioButton14.setVisible(false);
        jRadioButton11.setVisible(false);
      }
    boolean ACT, SAT, ILETS, TOFEL, PTE;
    public JFrame frame,callcls;

    public Bsc_Courses_Panel() {
        initComponents();
        init();
    }

    public Bsc_Courses_Panel(JFrame fr, String uni_name) {
        initComponents();
        init();
        frame = fr;
        university_name.setText(uni_name);
        System.out.println(uni_name);
    }
     public Bsc_Courses_Panel(JFrame fr,JFrame f, String uni_name) {
        initComponents();
        init();
        frame = fr;
        callcls=f;
        university_name.setText(uni_name);
        System.out.println(uni_name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        course_name = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        overview = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        program_duration = new javax.swing.JTextField();
        credits = new javax.swing.JTextField();
        tution_fees = new javax.swing.JTextField();
        application_fees = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        application_pre_req = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        sat_math_score = new javax.swing.JTextField();
        sat_rw_score = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        pte_score = new javax.swing.JTextField();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jRadioButton7 = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        tofel_score = new javax.swing.JTextField();
        jRadioButton9 = new javax.swing.JRadioButton();
        jLabel20 = new javax.swing.JLabel();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jLabel21 = new javax.swing.JLabel();
        act_score = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        Ilets_score = new javax.swing.JComboBox<>();
        university_name = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        Department = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        Semester = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        App_add = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        sat_total_score = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        gre_total = new javax.swing.JTextField();
        gmat_score = new javax.swing.JTextField();
        gre_quants = new javax.swing.JTextField();
        gre_awa = new javax.swing.JComboBox<>();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        gre_verbal = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        program = new combo_suggestion.ComboBoxSuggestion();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        check = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane1.setViewportView(jTextArea2);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("Add SAT Score?");

        setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Add Courses ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("University Name ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Course Name");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Overview");

        overview.setColumns(20);
        overview.setLineWrap(true);
        overview.setRows(5);
        overview.setWrapStyleWord(true);
        jScrollPane2.setViewportView(overview);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Program Duration");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Credits");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Tuition Fees");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Application Fees");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Application Pre Requisites");

        application_pre_req.setColumns(20);
        application_pre_req.setRows(5);
        jScrollPane3.setViewportView(application_pre_req);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Add SAT Score?");

        jRadioButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton1.setText("Yes");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton2.setText("No");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        sat_math_score.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                sat_math_scoreFocusLost(evt);
            }
        });
        sat_math_score.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sat_math_scoreActionPerformed(evt);
            }
        });
        sat_math_score.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sat_math_scoreKeyReleased(evt);
            }
        });

        sat_rw_score.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                sat_rw_scoreFocusLost(evt);
            }
        });
        sat_rw_score.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sat_rw_scoreActionPerformed(evt);
            }
        });
        sat_rw_score.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sat_rw_scoreKeyReleased(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("MATH SCORE");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("READ WRITE SCORE");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Add ACT Score?");

        jRadioButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton3.setText("Yes");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jRadioButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton4.setText("No");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("SCORE");

        pte_score.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pte_scoreKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pte_scoreKeyReleased(evt);
            }
        });

        jRadioButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton5.setText("Yes");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });

        jRadioButton6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton6.setText("No");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("SCORE");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("Add ILETS Score?");

        jRadioButton7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton7.setText("Yes");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setText("Add TOFEL Score?");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("SCORE");

        tofel_score.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tofel_scoreActionPerformed(evt);
            }
        });
        tofel_score.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tofel_scoreKeyReleased(evt);
            }
        });

        jRadioButton9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton9.setText("No");
        jRadioButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton9ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setText("Add PTE Score?");

        jRadioButton8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton8.setText("Yes");
        jRadioButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton8ActionPerformed(evt);
            }
        });

        jRadioButton10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton10.setText("No");
        jRadioButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton10ActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setText("SCORE");

        act_score.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                act_scoreActionPerformed(evt);
            }
        });
        act_score.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                act_scoreKeyReleased(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel22.setText("jLabel22");

        jLabel23.setText("jLabel23");

        jLabel24.setText("jLabel24");

        jLabel25.setText("jLabel25");

        jLabel26.setText("jLabel26");

        jLabel27.setText("jLabel27");

        Ilets_score.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "0.5", "1.0", "1.5", "2.0", "2.5", "3.0", "3.5", "4.0", "4.5", "5.0", "5.5", "6.0", "6.5", "7.0", "7.5", "8.0", "8.5", "9.0" }));

        university_name.setEditable(false);
        university_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                university_nameActionPerformed(evt);
            }
        });

        jLabel28.setText("jLabel28");

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel29.setText("Programe Type");

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel30.setText("Department Name");

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel31.setText("Number Of Semester");

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel32.setText("Application Website Address");

        App_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                App_addActionPerformed(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel33.setText("TOTAL SCORE");

        sat_total_score.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sat_total_scoreActionPerformed(evt);
            }
        });
        sat_total_score.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sat_total_scoreKeyReleased(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel34.setText("Add GMAT Score?");

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel35.setText("SCORE");

        jRadioButton11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton11.setText("No");
        jRadioButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton11ActionPerformed(evt);
            }
        });

        jRadioButton12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton12.setText("Yes");
        jRadioButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton12ActionPerformed(evt);
            }
        });

        gre_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gre_totalActionPerformed(evt);
            }
        });
        gre_total.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                gre_totalKeyReleased(evt);
            }
        });

        gmat_score.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gmat_scoreActionPerformed(evt);
            }
        });
        gmat_score.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                gmat_scoreKeyReleased(evt);
            }
        });

        gre_quants.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                gre_quantsFocusLost(evt);
            }
        });
        gre_quants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gre_quantsActionPerformed(evt);
            }
        });
        gre_quants.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                gre_quantsKeyReleased(evt);
            }
        });

        gre_awa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0.0", "0.1", "0.2", "0.3", "0.4", "0.5", "0.6", "0.7", "0.8", "0.9", "1.0", "1.1", "1.2", "1.3", "1.4", "1.5", "1.6", "1.7", "1.8", "1.9", "2.0", "2.1", "2.2", "2.3", "2.4", "2.5", "2.6", "2.7", "2.8", "2.9", "3.0", "3.1", "3.2", "3.3", "3.4", "3.5", "3.6", "3.7", "3.8", "3.9", "4.0", "4.1", "4.2", "4.3", "4.4", "4.5", "4.6", "4.7", "4.8", "4.9", "5.0", "5.1", "5.2", "5.3", "5.4", "5.5", "5.6", "5.7", "5.8", "5.9", "6.0" }));
        gre_awa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                gre_awaFocusLost(evt);
            }
        });
        gre_awa.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                gre_awaPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel36.setText("TOTAL");

        jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel37.setText("VERBAL ");

        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel38.setText("QUANTS");

        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel39.setText("AWA");

        jRadioButton13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton13.setText("Yes");
        jRadioButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton13ActionPerformed(evt);
            }
        });

        jRadioButton14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton14.setText("NO");
        jRadioButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton14ActionPerformed(evt);
            }
        });

        gre_verbal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                gre_verbalFocusLost(evt);
            }
        });
        gre_verbal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gre_verbalActionPerformed(evt);
            }
        });
        gre_verbal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                gre_verbalKeyReleased(evt);
            }
        });

        jLabel40.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel40.setText("Add GRE Score?");

        program.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bachelors Program", "Masters Program" }));

        jLabel41.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel41.setText("Apptitude Test");

        jLabel42.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel42.setText("English Test");

        jLabel43.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel43.setText("Mandatory?");

        check.setText("(Yes/No)");
        check.setBorder(null);
        check.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkMouseClicked(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Go Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(university_name)
                .addGap(280, 280, 280))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(program_duration)
                .addGap(285, 285, 285))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112)
                .addComponent(credits)
                .addGap(285, 285, 285))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(tution_fees)
                .addGap(285, 285, 285))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107)
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(Semester)))
                .addGap(290, 290, 290))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(jRadioButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jRadioButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(Ilets_score, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jRadioButton7)
                        .addGap(48, 48, 48)
                        .addComponent(jRadioButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(tofel_score, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(jRadioButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jRadioButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(pte_score, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(check, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)
                                .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(sat_math_score, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addComponent(sat_rw_score, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(sat_total_score, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(380, 380, 380)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton14))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton3)
                                .addGap(48, 48, 48)
                                .addComponent(jRadioButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(act_score, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(gre_verbal, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22)
                        .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(gre_quants, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(gre_awa, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20)
                        .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(gre_total, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(375, 375, 375)
                                .addComponent(jLabel28))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jRadioButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(jRadioButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(gmat_score, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 40, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addComponent(course_name))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(Department))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(program, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(290, 290, 290))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(365, 365, 365))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(App_add))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(application_fees)))
                .addGap(285, 285, 285))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel2))
                            .addComponent(university_name, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(course_name)
                                .addGap(2, 2, 2)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(program, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Department))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Semester))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel5))
                            .addComponent(program_duration, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(credits))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(tution_fees))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(application_fees))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32)
                            .addComponent(App_add))
                        .addGap(68, 68, 68)
                        .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel17))
                            .addComponent(jRadioButton5)
                            .addComponent(jRadioButton6)
                            .addComponent(jLabel15)
                            .addComponent(Ilets_score, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jRadioButton7)
                            .addComponent(jRadioButton9)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tofel_score, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jRadioButton8)
                            .addComponent(jRadioButton10)
                            .addComponent(jLabel21)
                            .addComponent(pte_score, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27))
                        .addGap(60, 60, 60)
                        .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(check, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel10))
                                    .addComponent(jRadioButton1))
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sat_math_score, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel23)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton2)
                                .addGap(20, 20, 20)
                                .addComponent(jLabel12))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(sat_rw_score, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel33))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(sat_total_score, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jRadioButton3)
                            .addComponent(jRadioButton4)
                            .addComponent(jLabel14)
                            .addComponent(act_score, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel40)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jRadioButton14)
                                .addComponent(jRadioButton13)))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel37))
                            .addComponent(gre_verbal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(gre_quants, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel39))
                            .addComponent(gre_awa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel36))
                            .addComponent(gre_total, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel34))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jRadioButton12))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jRadioButton11))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel35))
                            .addComponent(gmat_score, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel28)
                                .addGap(15, 15, 15))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)
                                .addGap(27, 27, 27))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel25)
                        .addGap(766, 766, 766))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        ACT = true;
        jLabel14.setVisible(true);
        act_score.setVisible(true);
        jRadioButton4.setSelected(false);

    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton10ActionPerformed
        jLabel21.setVisible(false);
        jLabel27.setVisible(false);
        pte_score.setVisible(false);
        pte_score.setText("");
        jRadioButton8.setSelected(false);
    }//GEN-LAST:event_jRadioButton10ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        jLabel15.setVisible(true);
        Ilets_score.setVisible(true);
        jRadioButton6.setSelected(false);
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        jLabel18.setVisible(true);
        tofel_score.setVisible(true);
        jRadioButton9.setSelected(false);
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton8ActionPerformed
        jLabel21.setVisible(true);
        pte_score.setVisible(true);
        jRadioButton10.setSelected(false);
    }//GEN-LAST:event_jRadioButton8ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        jLabel11.setVisible(true);
        sat_math_score.setVisible(true);
        jLabel12.setVisible(true);
        sat_rw_score.setVisible(true);
        sat_total_score.setVisible(true);
        jRadioButton2.setSelected(false);
        jLabel33.setVisible(true);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void sat_rw_scoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sat_rw_scoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sat_rw_scoreActionPerformed

    private void act_scoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_act_scoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_act_scoreActionPerformed
    String s = "";
    String ilets = "";
    private void sat_math_scoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sat_math_scoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sat_math_scoreActionPerformed
    String SAT_MATH = "";
    private void sat_math_scoreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sat_math_scoreKeyReleased
        char c = evt.getKeyChar();
        SAT_MATH += evt.getKeyChar();
        if (!Character.isDigit(c)) {
            JOptionPane.showMessageDialog(null, "Numeric value between 0 to 800");
            sat_math_score.setText("");
            SAT_MATH = "";
        } else {
            double d = Double.parseDouble(SAT_MATH);
            System.out.println(d);
            if (d < 0 || d > 800) {

                JOptionPane.showMessageDialog(null, "Numeric value between 0 to 800");
                sat_math_score.setText("");
                SAT_MATH = "";
            } else if (d >= 0 && d <= 800) {
                jLabel23.setVisible(false);
                jLabel23.setText("");

            }
        }
    }//GEN-LAST:event_sat_math_scoreKeyReleased

    private void tofel_scoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tofel_scoreActionPerformed

    }//GEN-LAST:event_tofel_scoreActionPerformed

    String tofel = "";
    private void tofel_scoreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tofel_scoreKeyReleased
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            JOptionPane.showMessageDialog(null, "Numeric value between 0 to 120");
            tofel_score.setText("");
            tofel = "";
        } else {
            tofel += evt.getKeyChar();
            System.out.println(tofel);
            double d = Double.parseDouble(tofel);
            if (d < 0 || d > 120) {
                tofel = "";

                JOptionPane.showMessageDialog(null, "Numeric value between 0 to 120");

                tofel_score.setText("");
            } else {
                jLabel26.setVisible(false);
                jLabel26.setText("");
            }

        }

    }//GEN-LAST:event_tofel_scoreKeyReleased
    String SAT_RW = "";
    private void sat_rw_scoreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sat_rw_scoreKeyReleased
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            JOptionPane.showMessageDialog(null, "Numeric value between 0 to 800");
            sat_rw_score.setText("");
            SAT_RW = "";
        } else {
            SAT_RW += evt.getKeyChar();
            System.out.println(SAT_RW);
            double d = Double.parseDouble(SAT_RW);
            if (d < 0 || d > 800) {
                SAT_RW = "";

                JOptionPane.showMessageDialog(null, "Numeric value between 0 to 800");
                sat_rw_score.setText("");
            }

        }
    }//GEN-LAST:event_sat_rw_scoreKeyReleased
    String act = "";
    private void act_scoreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_act_scoreKeyReleased
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            JOptionPane.showMessageDialog(null, "Numeric value between 0 to 36");
            act_score.setText("");
            act = "";
        } else {
            act += evt.getKeyChar();
            System.out.println(act);
            double d = Double.parseDouble(act);
            if (d < 0 || d > 36) {
                act = "";
                JOptionPane.showMessageDialog(null, "Numeric value between 0 to 36");

                act_score.setText("");
            }

        }
    }//GEN-LAST:event_act_scoreKeyReleased

    private void pte_scoreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pte_scoreKeyPressed

    }//GEN-LAST:event_pte_scoreKeyPressed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        jLabel14.setVisible(false);
        jLabel24.setVisible(false);
        act_score.setText("");
        act_score.setVisible(false);
        jRadioButton3.setSelected(false);

    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        jLabel15.setVisible(false);
        Ilets_score.setVisible(false);
        Ilets_score.setSelectedItem("");
        jLabel22.setVisible(false);
        jRadioButton5.setSelected(false);
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jRadioButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton9ActionPerformed
        jLabel18.setVisible(false);
        jLabel26.setVisible(false);
        tofel_score.setVisible(false);
        tofel_score.setText("");
        jRadioButton7.setSelected(false);
    }//GEN-LAST:event_jRadioButton9ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        jLabel11.setVisible(false);
        jLabel23.setVisible(false);
        jLabel25.setVisible(false);
        sat_math_score.setVisible(false);
        sat_math_score.setText("");
        sat_total_score.setVisible(false);
        sat_total_score.setText("");
        jLabel12.setVisible(false);
        sat_rw_score.setVisible(false);
        sat_rw_score.setText("");
        jRadioButton1.setSelected(false);
        jLabel33.setVisible(false);
    }//GEN-LAST:event_jRadioButton2ActionPerformed
    String pte = "";
    private void pte_scoreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pte_scoreKeyReleased
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            JOptionPane.showMessageDialog(null, "Numeric value between 0 to 90");
            pte_score.setText("");
            pte = "";
        } else {
            pte += evt.getKeyChar();
            System.out.println(pte);
            double d = Double.parseDouble(pte);
            if (d < 0 || d > 90) {
                pte = "";

                JOptionPane.showMessageDialog(null, "Numeric value between 0 to 90");
                pte_score.setText("");
            }

        }
    }//GEN-LAST:event_pte_scoreKeyReleased

    private void university_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_university_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_university_nameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            boolean flag= false;
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project", "root", "16ani");
            PreparedStatement st3 = con.prepareStatement("select Course_Name from bsc_courses where University_Name = ?");
          st3.setString(1,university_name.getText());
             ResultSet rs=st3.executeQuery();
           while(rs.next()){
               if (course_name.getText().equals(rs.getString("Course_Name"))){
                flag = true;   
                JOptionPane.showMessageDialog(null, "This Course has been added before");
               }
           }
           if(flag==false){
            String sql = "insert into bsc_courses values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            System.out.print("yes");
            PreparedStatement st = con.prepareStatement(sql);
            //Converting String into int using Integer.parseInt()  
            if ((university_name.getText().isEmpty()) || (course_name.getText().isEmpty()) || (overview.getText().isEmpty()) || (program_duration.getText().isEmpty()) || (credits.getText().isEmpty()) || (tution_fees.getText().isEmpty()) || (application_fees.getText().isEmpty()) || (application_pre_req.getText().isEmpty()) || (Semester.getText().isEmpty()) || (program.getSelectedIndex()==-1) || (Department.getText().isEmpty()) || App_add.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Some information is missing");
            } else {
                st.setString(1, university_name.getText());
                st.setString(2, course_name.getText());
                st.setString(3, (String) program.getSelectedItem());
                st.setString(4, Department.getText());
                st.setString(5, overview.getText());
                st.setInt(6, Integer.parseInt(Semester.getText()));
                int tf = 0, af = 0;
                double cr = 0, sm = 0, srw = 0, acts = 0, ils = 0, tfs = 0, pts = 0, stn = 0;
                /* if(program_duration.getText().isEmpty()==false)
                {
                    pd=Integer.parseInt(program_duration.getText());
                }*/
                st.setString(7, program_duration.getText());
                if (credits.getText().isEmpty() == false) {
                    cr = Double.parseDouble(credits.getText());
                }
                st.setDouble(8, cr);
                if (tution_fees.getText().isEmpty() == false) {
                    tf = Integer.parseInt(tution_fees.getText());
                }
                st.setInt(9, tf);
                if (application_fees.getText().isEmpty() == false) {
                    af = Integer.parseInt(application_fees.getText());
                }
                st.setInt(10, af);
                st.setString(11, application_pre_req.getText());
                if(jRadioButton2.isSelected()){
                    sm = 801;
                    srw = 801;
                    stn = 1601;
                }
           else if(sat_rw_score.getText().isEmpty() && sat_math_score.getText().isEmpty()){
                    if(sat_total_score.getText().isEmpty()){
                        sm=0;
                        srw=0;
                        stn=0;
                    }
                    else{
                        sm=801;
                        srw=801;
                        stn=Double.parseDouble(sat_total_score.getText());
                    }
                }

                else  {
                    sm = Double.parseDouble(sat_math_score.getText());
                     srw=Double.parseDouble(sat_rw_score.getText());
                      if(sat_total_score.getText().isEmpty())
                     stn= srw+sm;
                      else
                          stn =Double.parseDouble(sat_total_score.getText());
                }
                st.setDouble(12, sm);
                st.setDouble(13, srw);
                 st.setDouble(19, stn);
                 if(jRadioButton4.isSelected()){
                   acts=37;
                }
               else if(act_score.getText().isEmpty() == true){
                   acts=0;
               }
                else {
                    acts = Double.parseDouble(act_score.getText());
                }
                st.setDouble(14, acts);
                if (jRadioButton5.isSelected()) {
                    ils = Double.parseDouble(Ilets_score.getSelectedItem().toString());
                }
                else
                    ils =10;
                st.setDouble(15, ils);
                if(jRadioButton9.isSelected()){
                   tfs=121;
                }
               else if(tofel_score.getText().isEmpty() == true){
                   tfs=0;
               }
                else {
                    tfs= Double.parseDouble(tofel_score.getText());
                }
                st.setDouble(16, tfs);
                if(jRadioButton10.isSelected()){
                   pts=91;
                }
               else if(pte_score.getText().isEmpty() == true){
                   pts=0;
               }
                else {
                    pts= Double.parseDouble(pte_score.getText());
                }
                st.setDouble(17, pts);
                st.setString(18, App_add.getText());
                double gv = 0, gq = 0, gw = 0, gt = 0, gm = 0;
                if(jRadioButton14.isSelected()){
                    gv = 171;
                    gq = 171;
                    gw = 6.1;
                    gt = 347;
                }
            else if(gre_verbal.getText().isEmpty() && gre_quants.getText().isEmpty()){
                    if(gre_total.getText().isEmpty()){
                        gv=0;
                        gq=0;
                        gt=0;
                        gw= 0;
                    }
                    else{
                        gv=171;
                        gq=171;
                        gw= 6.1;
                        gt=Double.parseDouble(gre_total.getText());
                        
                    }
                }  
               else {
                    gv = Double.parseDouble(gre_verbal.getText());
                    gq=Double.valueOf(gre_quants.getText());
                    gw= (double) gre_awa.getSelectedItem();
                     if(gre_total.getText().isEmpty())
                  gt = gv+gq+ Double.valueOf((String) gre_awa.getSelectedItem());
                      else
                      gt = Double.valueOf(gre_total.getText());
                }
                st.setDouble(20, gv);
                st.setDouble(21, gq);
                st.setDouble(23, gt);
                st.setDouble(22, gw);
                 if(jRadioButton11.isSelected()){
                   gm=801;
                }
               else if(gmat_score.getText().isEmpty() == true){
                   gm=0;
               }
                else {
                    gm = Double.parseDouble(gmat_score.getText());
                }
                st.setDouble(24, gm);
                st.setBoolean(25,!check.isSelected());
                st.executeUpdate();
                JOptionPane.showMessageDialog(null, "Insertion Successful");
                String sql1 = "insert into project.semester_table (University_Name,Course_name) values(?,?); ";
                System.out.print("yes");
                PreparedStatement st1 = con.prepareStatement(sql1);
                st1.setString(1, university_name.getText());
                st1.setString(2, course_name.getText());
                st1.executeUpdate();
                callcls.setVisible(true);
                frame.dispose();
            }

            //double le=Double.parseDouble(LivingExpenses.getText());
            // st.setDouble(5,le);
            //  int i=Integer.parseInt(ApplicationFee.getText()); 
            // JOptionPane.showMessageDialog(null,"Insertion Successful");
           }} catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Insertion Is Not Successful");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void App_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_App_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_App_addActionPerformed

    private void sat_total_scoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sat_total_scoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sat_total_scoreActionPerformed
    String SAT_TOTAL = "";
    private void sat_total_scoreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sat_total_scoreKeyReleased
        char c = evt.getKeyChar();
        SAT_TOTAL += evt.getKeyChar();
        if (!Character.isDigit(c)) {
            JOptionPane.showMessageDialog(null, "Numeric value between 0 to 1600");
            sat_total_score.setText("");
            SAT_TOTAL = "";
        } else {
            double d = Double.parseDouble(SAT_TOTAL);
            System.out.println(d);
            if (d < 0 || d > 1600) {

                JOptionPane.showMessageDialog(null, "Numeric value between 0 to 1600");
                sat_total_score.setText("");
                SAT_TOTAL = "";
            } else if (d >= 0 && d <= 1600) {
                jLabel23.setVisible(false);
                jLabel23.setText("");

            }
        }
    }//GEN-LAST:event_sat_total_scoreKeyReleased

    private void jRadioButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton11ActionPerformed
        jLabel35.setVisible(false);
        gmat_score.setVisible(false);
        gmat_score.setText("");
        jRadioButton12.setSelected(false);
    }//GEN-LAST:event_jRadioButton11ActionPerformed

    private void jRadioButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton12ActionPerformed
        jLabel35.setVisible(true);
        gmat_score.setVisible(true);
        jRadioButton11.setSelected(false);
    }//GEN-LAST:event_jRadioButton12ActionPerformed

    private void gre_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gre_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gre_totalActionPerformed
    String GRE_TOTAL = "";
    private void gre_totalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gre_totalKeyReleased
        char c = evt.getKeyChar();
        GRE_TOTAL += evt.getKeyChar();
        if (!Character.isDigit(c)) {
            JOptionPane.showMessageDialog(null, "Numeric value between 0 to 340");
            gre_total.setText("");
            GRE_TOTAL = "";
        } else {
            double d = Double.parseDouble(GRE_TOTAL);
            System.out.println(d);
            if (d < 0 || d > 340) {

                JOptionPane.showMessageDialog(null, "Numeric value between 0 to 340");
                gre_total.setText("");
                GRE_TOTAL = "";
            } else if (d >= 0 && d <= 340) {
                jLabel23.setVisible(false);
                jLabel23.setText("");

            }
        }
    }//GEN-LAST:event_gre_totalKeyReleased

    private void gmat_scoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gmat_scoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gmat_scoreActionPerformed
    String GMAT = "";
    private void gmat_scoreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gmat_scoreKeyReleased
        char c = evt.getKeyChar();
        GMAT += evt.getKeyChar();
        if (!Character.isDigit(c)) {
            JOptionPane.showMessageDialog(null, "Numeric value between 0 to 800");
            gmat_score.setText("");
            GMAT = "";
        } else {
            double d = Double.parseDouble(GMAT);
            System.out.println(d);
            if (d < 0 || d > 800) {

                JOptionPane.showMessageDialog(null, "Numeric value between 0 to 800");
                gmat_score.setText("");
                GMAT = "";
            } else if (d >= 0 && d <= 800) {
                jLabel23.setVisible(false);
                jLabel23.setText("");

            }
        }
    }//GEN-LAST:event_gmat_scoreKeyReleased

    private void gre_quantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gre_quantsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gre_quantsActionPerformed
    String GRE_QUANTS = "";
    private void gre_quantsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gre_quantsKeyReleased
        char c = evt.getKeyChar();
        GRE_QUANTS += evt.getKeyChar();
        if (!Character.isDigit(c)) {
            JOptionPane.showMessageDialog(null, "Numeric value between 0 to 170");
            gre_quants.setText("");
            GRE_QUANTS = "";
        } else {
            double d = Double.parseDouble(GRE_QUANTS);
            System.out.println(d);
            if (d < 0 || d > 170) {

                JOptionPane.showMessageDialog(null, "Numeric value between 0 to 170");
                gre_quants.setText("");
                GRE_QUANTS = "";
            } else if (d >= 0 && d <= 170) {
                jLabel23.setVisible(false);
                jLabel23.setText("");

            }
        }
    }//GEN-LAST:event_gre_quantsKeyReleased

    private void jRadioButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton13ActionPerformed
        jLabel37.setVisible(true);
        gre_verbal.setVisible(true);
        jLabel38.setVisible(true);
        gre_quants.setVisible(true);
        jLabel39.setVisible(true);
        gre_awa.setVisible(true);
        jLabel36.setVisible(true);
        gre_total.setVisible(true);
        jRadioButton14.setSelected(false);
    }//GEN-LAST:event_jRadioButton13ActionPerformed

    private void jRadioButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton14ActionPerformed
        jLabel37.setVisible(false);
        gre_verbal.setVisible(false);
        gre_verbal.setText("");
        jLabel38.setVisible(false);
        gre_quants.setVisible(false);
        gre_quants.setText("");
        jLabel39.setVisible(false);
        gre_awa.setVisible(false);
        gre_awa.setSelectedIndex(0);
        jLabel36.setVisible(false);
        gre_total.setVisible(false);
        gre_total.setText("");
        jRadioButton13.setSelected(false);
    }//GEN-LAST:event_jRadioButton14ActionPerformed

    private void gre_verbalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gre_verbalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gre_verbalActionPerformed
    String GRE_VERBAL = "";
    private void gre_verbalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gre_verbalKeyReleased
        char c = evt.getKeyChar();
        GRE_VERBAL += evt.getKeyChar();
        if (!Character.isDigit(c)) {
            JOptionPane.showMessageDialog(null, "Numeric value between 0 to 170");
            gre_verbal.setText("");
            GRE_VERBAL = "";
        } else {
            double d = Double.parseDouble(GRE_VERBAL);
            System.out.println(d);
            if (d < 0 || d > 170) {

                JOptionPane.showMessageDialog(null, "Numeric value between 0 to 170");
                gre_verbal.setText("");
                GRE_VERBAL = "";
            } else if (d >= 0 && d <= 170) {
                jLabel23.setVisible(false);
                jLabel23.setText("");

            }
        }
    }//GEN-LAST:event_gre_verbalKeyReleased

    private void checkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkMouseClicked
        if(!check.isSelected()){
        jLabel10.setVisible(false);
        jLabel13.setVisible(false);
        jLabel34.setVisible(false);
        jLabel40.setVisible(false);
        jRadioButton1.setVisible(false);
        jRadioButton3.setVisible(false);
        jRadioButton12.setVisible(false);
        jRadioButton13.setVisible(false);
         jRadioButton2.setVisible(false);
        jRadioButton4.setVisible(false);
        jRadioButton14.setVisible(false);
        jRadioButton11.setVisible(false);
    
    }
        else{
             jLabel10.setVisible(true);
        jLabel13.setVisible(true);
        jLabel34.setVisible(true);
        jLabel40.setVisible(true);
        jRadioButton1.setVisible(true);
        jRadioButton3.setVisible(true);
        jRadioButton12.setVisible(true);
        jRadioButton13.setVisible(true);
         jRadioButton2.setVisible(true);
        jRadioButton4.setVisible(true);
        jRadioButton14.setVisible(true);
        jRadioButton11.setVisible(true);
        }
    }//GEN-LAST:event_checkMouseClicked

    private void sat_rw_scoreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sat_rw_scoreFocusLost
       if(!sat_rw_score.getText().isEmpty() && !sat_math_score.getText().isEmpty()){
           double d=Double.parseDouble(sat_rw_score.getText());
           double e=Double.parseDouble(sat_math_score.getText());
           sat_total_score.setText(String.valueOf(d+e));}
    }//GEN-LAST:event_sat_rw_scoreFocusLost

    private void sat_math_scoreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sat_math_scoreFocusLost
 if(!sat_rw_score.getText().isEmpty() && !sat_math_score.getText().isEmpty()){
           double d=Double.parseDouble(sat_rw_score.getText());
           double e=Double.parseDouble(sat_math_score.getText());
           sat_total_score.setText(String.valueOf(d+e));}     
    }//GEN-LAST:event_sat_math_scoreFocusLost

    private void gre_verbalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_gre_verbalFocusLost
       if(!gre_verbal.getText().isEmpty() && !gre_quants.getText().isEmpty()){
           double d=Double.parseDouble(gre_verbal.getText());
           double e=Double.parseDouble(gre_quants.getText());
           double f = Double.parseDouble((String) gre_awa.getSelectedItem());
           gre_total.setText(String.valueOf(d+e+f));}
    }//GEN-LAST:event_gre_verbalFocusLost

    private void gre_quantsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_gre_quantsFocusLost
 if(!gre_verbal.getText().isEmpty() && !gre_quants.getText().isEmpty()){
           double d=Double.parseDouble(gre_verbal.getText());
           double e=Double.parseDouble(gre_quants.getText());
           double f = Double.parseDouble((String) gre_awa.getSelectedItem());
           gre_total.setText(String.valueOf(d+e+f));}       
    }//GEN-LAST:event_gre_quantsFocusLost

    private void gre_awaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_gre_awaFocusLost
 if(!gre_verbal.getText().isEmpty() && !gre_quants.getText().isEmpty()){
           double d=Double.parseDouble(gre_verbal.getText());
           double e=Double.parseDouble(gre_quants.getText());
           double f = Double.parseDouble((String) gre_awa.getSelectedItem());
           gre_total.setText(String.valueOf(d+e+f));}       
    }//GEN-LAST:event_gre_awaFocusLost

    private void gre_awaPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_gre_awaPopupMenuWillBecomeInvisible
       if(!gre_verbal.getText().isEmpty() && !gre_quants.getText().isEmpty()){
           double d=Double.parseDouble(gre_verbal.getText());
           double e=Double.parseDouble(gre_quants.getText());
           double f = Double.parseDouble((String) gre_awa.getSelectedItem());
           gre_total.setText(String.valueOf(d+e+f));}    
    }//GEN-LAST:event_gre_awaPopupMenuWillBecomeInvisible

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       callcls.setVisible(true);
       frame.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField App_add;
    private javax.swing.JTextField Department;
    private javax.swing.JComboBox<String> Ilets_score;
    private javax.swing.JTextField Semester;
    private javax.swing.JTextField act_score;
    private javax.swing.JTextField application_fees;
    private javax.swing.JTextArea application_pre_req;
    private javax.swing.JCheckBox check;
    private javax.swing.JTextField course_name;
    private javax.swing.JTextField credits;
    private javax.swing.JTextField gmat_score;
    private javax.swing.JComboBox<String> gre_awa;
    private javax.swing.JTextField gre_quants;
    private javax.swing.JTextField gre_total;
    private javax.swing.JTextField gre_verbal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea overview;
    private combo_suggestion.ComboBoxSuggestion program;
    private javax.swing.JTextField program_duration;
    private javax.swing.JTextField pte_score;
    private javax.swing.JTextField sat_math_score;
    private javax.swing.JTextField sat_rw_score;
    private javax.swing.JTextField sat_total_score;
    private javax.swing.JTextField tofel_score;
    private javax.swing.JTextField tution_fees;
    private javax.swing.JTextField university_name;
    // End of variables declaration//GEN-END:variables
}
