
package udream;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import static java.lang.System.out;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import scrollbar.ScrollBarCustom;

public class Study_Overview extends javax.swing.JPanel {
String s;

   String arr[] = {"Hello", "No", "Bye"};
    public Study_Overview() {
         initComponents();
          System.out.println("DDD"+jLabel1.getWidth());
    }
    public Study_Overview(String st) {
        s= st;
        initComponents();
         jTable1.setTableHeader(null);
      jTable1.setBackground(Color.white);
      jTable1.getColumn("Title 1").setCellRenderer(new myTableCellRenderer());
      info();
        
      
      jScrollPane2.setVerticalScrollBar(new ScrollBarCustom());
       jScrollPane1.setVerticalScrollBar(new ScrollBarCustom());
       jLabel4.setText(st+" As a Study Destination: Highlights");
    }
void info(){
    try {
        jTable1.setDefaultRenderer(Object.class, new MultiLineCellRenderer());
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project", "root", "16ani");
        PreparedStatement st = con.prepareStatement("select * from study_guide_main_table where country_name = ?");
        st.setString(1,s);
         ResultSet rs = st.executeQuery();
        if(rs.next()&&rs.getBytes("picture")!=null){
          byte[] img = rs.getBytes("picture");
               ImageIcon image = new ImageIcon(img);
               Image im= image.getImage();
               Image myimg = im.getScaledInstance(1100,204,Image.SCALE_SMOOTH);
               ImageIcon ni = new ImageIcon(myimg);
             jLabel1.setIcon(ni);
        }
        Overview.setText(rs.getString("overview"));
          st = con.prepareStatement("select * from study_destination where country_name= ?");
        st.setString(1,s);
        ResultSet rs1 = st.executeQuery();
        rs1.next();
        PreparedStatement st1 = con.prepareStatement("SHOW COLUMNS FROM study_destination");
        ResultSet rs2 = st1.executeQuery();
        int i =0;
        rs2.next();
        while(rs2.next()){
         JLabel a= new JLabel();
      
        jTable1.setFont(new Font("Segoe UI Emoji", Font.PLAIN, 18));
          a.setFont(new Font("Segoe UI Emoji", Font.BOLD, 18));
        String c =rs2.getString("Field");
        a.setText(c);
        String b = rs1.getString(c);
        int d =(((b.length()/60)*22)+30);
        System.out.println(b.length()+ " "+ d);
        DefaultTableModel tblmodel= (DefaultTableModel)jTable1.getModel();
        tblmodel.addRow(new Object[]{a,b});
         jTable1.setRowHeight(i,d);
           jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
         jScrollPane1.setViewportBorder(null);
        jScrollPane1.getViewport().setBorder(null);
        i++;}
    } catch (SQLException | ClassNotFoundException ex) {
        Logger.getLogger(Study_Overview.class.getName()).log(Level.SEVERE, null, ex);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        panelRound1 = new test.PanelRound();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Overview = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(250, 250, 202));

        jScrollPane1.setBorder(null);

        jTable1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 15)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setEnabled(false);
        jTable1.setFocusable(false);
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setOpaque(false);
        jTable1.setRowHeight(46);
        jTable1.setRowSelectionAllowed(false);
        jTable1.setShowGrid(true);
        jScrollPane1.setViewportView(jTable1);

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setRoundBottomLeft(24);
        panelRound1.setRoundBottomRight(24);
        panelRound1.setRoundTopLeft(24);
        panelRound1.setRoundTopRight(24);

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel2.setText("Overview");

        jLabel3.setText("_______________________________________________________________________________________________________________________________________________________");

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        Overview.setEditable(false);
        Overview.setColumns(20);
        Overview.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        Overview.setLineWrap(true);
        Overview.setRows(5);
        Overview.setWrapStyleWord(true);
        Overview.setBorder(null);
        jScrollPane2.setViewportView(Overview);

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane2)
                .addGap(16, 16, 16))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel4.setText("USA As a Study Destination: Highlights");

        jLabel5.setText("jLabel5");

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(36, 36, 36))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(106, 106, 106))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1)
                .addGap(107, 107, 107))
            .addGroup(layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jButton1)
                .addGap(137, 137, 137)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(jLabel5))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          String t = jTextField1.getText();
        for (int i = 0; i < 3; i++) {
            if (t.equals(arr[i])) {
              //  "/images/Logo1.png"
                String s="/images/"+t+".png";
                System.out.println(s);
                 System.out.println(s.equals( "/images/Hello.png"));
               ImageIcon icon = new ImageIcon(getClass().getResource(s));
               Image img = icon.getImage();
               Image imgScale = img.getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_SMOOTH);
               ImageIcon scaledIcon = new ImageIcon(imgScale);
               jLabel1.setIcon(scaledIcon);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Overview;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private test.PanelRound panelRound1;
    // End of variables declaration//GEN-END:variables
}
