/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package udream;

import udream.MultiLineCellRenderer;
import java.awt.Color;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import net.proteanit.sql.DbUtils;
import scrollbar.ScrollBarCustom;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Rayhan
 */
public class Study_Guide_Popular_University extends javax.swing.JPanel {

    String s;
    public Study_Guide_Popular_University(String str) {
        initComponents();
        s=str;
         jScrollPane1.setVerticalScrollBar(new ScrollBarCustom());
         info();
         jLabel1.setText("Popular Universities in "+str);
    }
void info(){
        try {
             jTable1.setDefaultRenderer(Object.class, new MultiLineCellRenderer());
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project", "root", "16ani");
           // String a = "World Ranking";
            PreparedStatement st = con.prepareStatement("select University_Name as University ,Ranking from university_info where Country = ? ORDER BY Ranking");
            st.setString(1,s);
            ResultSet rs = st.executeQuery(); 
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            jTable1.setBackground(new Color(255,255,255));
            DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
             DefaultTableCellRenderer headerRenderer1 = new DefaultTableCellRenderer();
             headerRenderer1.setHorizontalAlignment(SwingConstants.CENTER);
              headerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
           headerRenderer.setBackground(new Color(153,153,255));
         jTable1.getColumnModel().getColumn(0).setHeaderRenderer(headerRenderer);
          jTable1.getColumnModel().getColumn(1).setHeaderRenderer(headerRenderer);
           jTable1.getColumnModel().getColumn(1).setCellRenderer(headerRenderer1);
            jTable1.setSelectionBackground(Color.lightGray);
              jTable1.setSelectionForeground(Color.white);
         jTable1.getColumnModel().getColumn(1).setMaxWidth(90);
           jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
         jScrollPane1.setViewportBorder(null);
        jScrollPane1.getViewport().setBorder(null);
         
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(Study_Guide_Popular_University.class.getName()).log(Level.SEVERE, null, ex);
        }
}    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(250, 250, 202));

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel1.setText("Popular Universities in USA");

        jScrollPane1.setBorder(null);
        jScrollPane1.setFocusable(false);

        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setFocusable(false);
        jTable1.setGridColor(new java.awt.Color(0, 0, 0));
        jTable1.setRowHeight(60);
        jTable1.setShowGrid(true);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE))
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
