package udream;
///[250,250,231]

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Image;
import java.awt.Rectangle;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollBar;
import javax.swing.JScrollPane;
import scrollbar.ScrollBarCustom;
import test.PanelRound;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import scrollclspackage.CourseCls;

public class University_Page extends javax.swing.JPanel {

    JFrame cls, callcls;
    String str;

    public University_Page(JFrame frame, String s) {
        initComponents();
        str = s;
        cls = frame;
        AboutScroll.setVerticalScrollBar(new ScrollBarCustom());
        ContactScroll.setVerticalScrollBar(new ScrollBarCustom());
        CourseScroll.setVerticalScrollBar(new ScrollBarCustom());
        System.out.println(Photo.getWidth());
       
        info();
        callcls=new HOME();
       
    }

    public University_Page(JFrame frame, String s, JFrame f) {
        initComponents();
        str = s;
        cls = frame;
        callcls = f;
        AboutScroll.setVerticalScrollBar(new ScrollBarCustom());
        ContactScroll.setVerticalScrollBar(new ScrollBarCustom());
        CourseScroll.setVerticalScrollBar(new ScrollBarCustom());
      
        info();
       
    }
    DefaultListModel model = new DefaultListModel();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UniName = new javax.swing.JPanel();
        Name = new javax.swing.JLabel();
        Country = new javax.swing.JLabel();
        Established = new javax.swing.JLabel();
        imageAvatar1 = new main.ImageAvatar();
        jLabel1 = new javax.swing.JLabel();
        ContactPanel = new test.PanelRound();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Fbfield = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        ContactScroll = new javax.swing.JScrollPane();
        Addressfield = new javax.swing.JTextArea();
        jLabel24 = new javax.swing.JLabel();
        Emailfield = new javax.swing.JTextField();
        Website = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        CostPanel = new test.PanelRound();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        TutionfeeField = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        BachelorExpenses = new javax.swing.JTextField();
        OnCampusExpenses = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        AboutPanel = new test.PanelRound();
        jLabel9 = new javax.swing.JLabel();
        AboutScroll = new javax.swing.JScrollPane();
        AboutText = new javax.swing.JTextArea();
        jLabel28 = new javax.swing.JLabel();
        RankingPanel = new test.PanelRound();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Rankingfield = new javax.swing.JTextArea();
        jLabel29 = new javax.swing.JLabel();
        AdmissionPanel = new test.PanelRound();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Applicationfee = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        CoursePanel = new test.PanelRound();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        CourseScroll = new javax.swing.JScrollPane();
        CourseList = new javax.swing.JList<>();
        jLabel31 = new javax.swing.JLabel();
        PhotoPanel = new test.PanelRound();
        jLabel13 = new javax.swing.JLabel();
        Photo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(250, 250, 202));

        UniName.setBackground(new java.awt.Color(255, 255, 255));
        UniName.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Name.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        Name.setText("dfdsf");
        UniName.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 890, 60));

        Country.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Country.setForeground(new java.awt.Color(102, 102, 102));
        Country.setText("fgfdg");
        UniName.add(Country, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 140, 30));

        Established.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Established.setForeground(new java.awt.Color(102, 102, 102));
        Established.setText("fdgfd");
        UniName.add(Established, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 230, 30));

        imageAvatar1.setBorderSize(1);
        UniName.add(imageAvatar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 120));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 51));
        jLabel1.setText("Go Back>>");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        UniName.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 120, -1));

        ContactPanel.setBackground(new java.awt.Color(255, 255, 255));
        ContactPanel.setRoundBottomLeft(24);
        ContactPanel.setRoundBottomRight(24);
        ContactPanel.setRoundTopLeft(24);
        ContactPanel.setRoundTopRight(24);
        ContactPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel6.setText("Contact Info");
        ContactPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 13, 180, 27));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("Facebook");
        ContactPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 120, 26));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 255));
        jLabel8.setText("Website");
        ContactPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 200, 30));

        Fbfield.setEditable(false);
        Fbfield.setBackground(new java.awt.Color(255, 255, 255));
        Fbfield.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Fbfield.setForeground(new java.awt.Color(0, 153, 0));
        Fbfield.setBorder(null);
        ContactPanel.add(Fbfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 730, 40));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 255));
        jLabel12.setText("Email Address");
        ContactPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 156, 26));

        ContactScroll.setBorder(null);

        Addressfield.setEditable(false);
        Addressfield.setColumns(20);
        Addressfield.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Addressfield.setRows(2);
        Addressfield.setBorder(null);
        ContactScroll.setViewportView(Addressfield);

        ContactPanel.add(ContactScroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 780, 50));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 51, 255));
        jLabel24.setText("University Address");
        ContactPanel.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 200, 30));

        Emailfield.setEditable(false);
        Emailfield.setBackground(new java.awt.Color(255, 255, 255));
        Emailfield.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Emailfield.setForeground(new java.awt.Color(0, 153, 0));
        Emailfield.setBorder(null);
        Emailfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailfieldActionPerformed(evt);
            }
        });
        ContactPanel.add(Emailfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 780, 40));

        Website.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Website.setForeground(new java.awt.Color(0, 153, 0));
        Website.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                WebsiteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                WebsiteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                WebsiteMouseExited(evt);
            }
        });
        ContactPanel.add(Website, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 310, 30));

        jLabel32.setForeground(new java.awt.Color(102, 102, 102));
        jLabel32.setText("_____________________________________________________________________________________________________________________________________________________________________________________________________________________");
        ContactPanel.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        CostPanel.setBackground(new java.awt.Color(255, 255, 255));
        CostPanel.setRoundBottomLeft(24);
        CostPanel.setRoundBottomRight(24);
        CostPanel.setRoundTopLeft(24);
        CostPanel.setRoundTopRight(24);

        jLabel18.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel18.setText("Cost");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 255));
        jLabel19.setText("Living Expenses");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 255));
        jLabel20.setText("Average Tution Fee");

        TutionfeeField.setEditable(false);
        TutionfeeField.setBackground(new java.awt.Color(255, 255, 255));
        TutionfeeField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TutionfeeField.setBorder(null);

        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setText("Avarage Living Expenses (Bachelors)");

        jLabel22.setForeground(new java.awt.Color(102, 102, 102));
        jLabel22.setText("Avarage On Campus Living Expense");

        BachelorExpenses.setEditable(false);
        BachelorExpenses.setBackground(new java.awt.Color(255, 255, 255));
        BachelorExpenses.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BachelorExpenses.setForeground(new java.awt.Color(0, 153, 0));
        BachelorExpenses.setBorder(null);
        BachelorExpenses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BachelorExpensesActionPerformed(evt);
            }
        });

        OnCampusExpenses.setEditable(false);
        OnCampusExpenses.setBackground(new java.awt.Color(255, 255, 255));
        OnCampusExpenses.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        OnCampusExpenses.setForeground(new java.awt.Color(0, 153, 0));
        OnCampusExpenses.setBorder(null);

        jLabel25.setForeground(new java.awt.Color(102, 102, 102));
        jLabel25.setText("_____________________________________________________________________________________________________________________________________________________________________________________________________________________");

        javax.swing.GroupLayout CostPanelLayout = new javax.swing.GroupLayout(CostPanel);
        CostPanel.setLayout(CostPanelLayout);
        CostPanelLayout.setHorizontalGroup(
            CostPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CostPanelLayout.createSequentialGroup()
                .addGroup(CostPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CostPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CostPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CostPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(TutionfeeField, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CostPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CostPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(220, 220, 220)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CostPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(BachelorExpenses, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(150, 150, 150)
                        .addComponent(OnCampusExpenses, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(CostPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1182, Short.MAX_VALUE))
        );
        CostPanelLayout.setVerticalGroup(
            CostPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CostPanelLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(TutionfeeField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(CostPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(CostPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BachelorExpenses, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OnCampusExpenses, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(CostPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CostPanelLayout.createSequentialGroup()
                    .addGap(50, 50, 50)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(210, Short.MAX_VALUE)))
        );

        AboutPanel.setBackground(new java.awt.Color(255, 255, 255));
        AboutPanel.setRoundBottomLeft(24);
        AboutPanel.setRoundBottomRight(24);
        AboutPanel.setRoundTopLeft(24);
        AboutPanel.setRoundTopRight(24);

        jLabel9.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel9.setText("About");

        AboutScroll.setBackground(new java.awt.Color(255, 255, 255));
        AboutScroll.setBorder(null);

        AboutText.setEditable(false);
        AboutText.setColumns(20);
        AboutText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AboutText.setLineWrap(true);
        AboutText.setRows(2);
        AboutText.setWrapStyleWord(true);
        AboutText.setBorder(null);
        AboutScroll.setViewportView(AboutText);

        jLabel28.setForeground(new java.awt.Color(102, 102, 102));
        jLabel28.setText("_____________________________________________________________________________________________________________________________________________________________________________________________________________________");

        javax.swing.GroupLayout AboutPanelLayout = new javax.swing.GroupLayout(AboutPanel);
        AboutPanel.setLayout(AboutPanelLayout);
        AboutPanelLayout.setHorizontalGroup(
            AboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AboutPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(AboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AboutPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(AboutPanelLayout.createSequentialGroup()
                        .addComponent(AboutScroll)
                        .addGap(180, 180, 180))))
            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        AboutPanelLayout.setVerticalGroup(
            AboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AboutPanelLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(AboutScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        RankingPanel.setBackground(new java.awt.Color(255, 255, 255));
        RankingPanel.setRoundBottomLeft(24);
        RankingPanel.setRoundBottomRight(24);
        RankingPanel.setRoundTopLeft(24);
        RankingPanel.setRoundTopRight(24);
        RankingPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel5.setText("Ranking");
        RankingPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 13, 115, 28));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        Rankingfield.setEditable(false);
        Rankingfield.setColumns(20);
        Rankingfield.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Rankingfield.setLineWrap(true);
        Rankingfield.setRows(1);
        Rankingfield.setWrapStyleWord(true);
        Rankingfield.setBorder(null);
        jScrollPane1.setViewportView(Rankingfield);

        RankingPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 780, 40));

        jLabel29.setForeground(new java.awt.Color(102, 102, 102));
        jLabel29.setText("_____________________________________________________________________________________________________________________________________________________________________________________________________________________");
        RankingPanel.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        AdmissionPanel.setBackground(new java.awt.Color(255, 255, 255));
        AdmissionPanel.setRoundBottomLeft(24);
        AdmissionPanel.setRoundBottomRight(24);
        AdmissionPanel.setRoundTopLeft(24);
        AdmissionPanel.setRoundTopRight(24);
        AdmissionPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel10.setText("Admission");
        AdmissionPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 13, 130, 27));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 255));
        jLabel11.setText("Application Fee");
        AdmissionPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 156, 26));

        Applicationfee.setEditable(false);
        Applicationfee.setBackground(new java.awt.Color(255, 255, 255));
        Applicationfee.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Applicationfee.setForeground(new java.awt.Color(0, 153, 0));
        Applicationfee.setBorder(null);
        AdmissionPanel.add(Applicationfee, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 730, 40));

        jLabel30.setForeground(new java.awt.Color(102, 102, 102));
        jLabel30.setText("_____________________________________________________________________________________________________________________________________________________________________________________________________________________");
        AdmissionPanel.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        CoursePanel.setBackground(new java.awt.Color(255, 255, 255));
        CoursePanel.setRoundBottomLeft(24);
        CoursePanel.setRoundBottomRight(24);
        CoursePanel.setRoundTopLeft(24);
        CoursePanel.setRoundTopRight(24);

        jLabel16.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel16.setText("Courses");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Click from the list to show detaild infromation about the courses");

        CourseScroll.setBorder(null);

        CourseList.setBackground(new java.awt.Color(255, 255, 204));
        CourseList.setFixedCellHeight(30);
        CourseList.setSelectionBackground(new java.awt.Color(255, 0, 0));
        CourseList.setVisibleRowCount(-1);
        CourseList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CourseListMouseClicked(evt);
            }
        });
        CourseList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                CourseListValueChanged(evt);
            }
        });
        CourseScroll.setViewportView(CourseList);

        jLabel31.setForeground(new java.awt.Color(102, 102, 102));
        jLabel31.setText("_____________________________________________________________________________________________________________________________________________________________________________________________________________________");

        javax.swing.GroupLayout CoursePanelLayout = new javax.swing.GroupLayout(CoursePanel);
        CoursePanel.setLayout(CoursePanelLayout);
        CoursePanelLayout.setHorizontalGroup(
            CoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CoursePanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(CoursePanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(CoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CoursePanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(CourseScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CoursePanelLayout.setVerticalGroup(
            CoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CoursePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CourseScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        PhotoPanel.setBackground(new java.awt.Color(255, 255, 255));
        PhotoPanel.setRoundBottomLeft(24);
        PhotoPanel.setRoundBottomRight(24);
        PhotoPanel.setRoundTopLeft(24);
        PhotoPanel.setRoundTopRight(24);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setText("Photo");

        Photo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout PhotoPanelLayout = new javax.swing.GroupLayout(PhotoPanel);
        PhotoPanel.setLayout(PhotoPanelLayout);
        PhotoPanelLayout.setHorizontalGroup(
            PhotoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PhotoPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Photo, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PhotoPanelLayout.setVerticalGroup(
            PhotoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PhotoPanelLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(Photo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(7, 7, 7))
            .addGroup(PhotoPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(289, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UniName, javax.swing.GroupLayout.PREFERRED_SIZE, 1350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(AboutPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CostPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(RankingPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1182, Short.MAX_VALUE))
                            .addComponent(AdmissionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CoursePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ContactPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1192, Short.MAX_VALUE)
                            .addComponent(PhotoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(UniName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(AboutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(CostPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(RankingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(AdmissionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(CoursePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(ContactPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(PhotoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
 void info() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project", "root", "16ani");
            PreparedStatement st = con.prepareStatement("select * from university_info where University_Name = ?");
            st.setString(1, str);
            ResultSet rs = st.executeQuery();
            if (rs.next()) {
                Name.setText(rs.getString("University_Name"));
                if (rs.getBytes("Icon") != null) {
                    byte[] img = rs.getBytes("Icon");
                    ImageIcon image = new ImageIcon(img);
                    Image im = image.getImage();
                    Image myimg = im.getScaledInstance(110, 110, Image.SCALE_SMOOTH);
                    ImageIcon ni = new ImageIcon(myimg);
                    //    Icon.setIcon(ni);
                    imageAvatar1.setImage(ni);
                }
            }
            Country.setText(rs.getString("Country"));
            Established.setText("Established in " + rs.getString("EstablishedYear"));
            AboutText.setText(rs.getString("About"));
            TutionfeeField.setText("$" + (rs.getString("Cost")));
            BachelorExpenses.setText("$" + Double.toString(rs.getDouble("LivingExpensesBachelor")));
            OnCampusExpenses.setText("$" + Double.toString(rs.getDouble("LivingExpensesOnCampus")));
            Rankingfield.setText("#" + Integer.toString(rs.getInt("Ranking")));
            Applicationfee.setText("$" + Integer.toString(rs.getInt("ApplicationFee")));
           if(rs.getBytes("Picture")!=null)
           {
            byte[] img = rs.getBytes("Picture");
            ImageIcon image = new ImageIcon(img);
            Image im = image.getImage();
            Image myimg = im.getScaledInstance(516, 280, Image.SCALE_SMOOTH);
            ImageIcon ni = new ImageIcon(myimg);
            Photo.setIcon(ni);
           }
            Website.setText(rs.getString("Website"));
            Addressfield.setText(rs.getString("UniversityAddress"));
            Emailfield.setText(rs.getString("Email"));
            Fbfield.setText(rs.getString("FacebookID"));
            PreparedStatement st1 = con.prepareStatement("select * from bsc_courses where University_Name = ?");
            st1.setString(1, str);
            ResultSet rs1 = st1.executeQuery();
            while (rs1.next()) {
                model.addElement(rs1.getString("Course_Name"));
            }
            CourseList.setModel(model);

            int a = CourseList.getModel().getSize();
            if (a < 6) {
                if (a == 3) {
                    CourseList.setFixedCellHeight(53);
                }
                if (a == 4) {
                    CourseList.setFixedCellHeight(42);
                }
                if (a == 5) {
                    CourseList.setFixedCellHeight(34);
                }
            }
            System.out.println(a);
        } catch (SQLException ex) {
            Logger.getLogger(University_Page.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(University_Page.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    private void EmailfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailfieldActionPerformed

    private void WebsiteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WebsiteMouseClicked
        try {
            Website.setForeground(Color.BLUE.darker());
            Desktop.getDesktop().browse(new URI("www." + Website.getText()));
        } catch (URISyntaxException ex) {
            Logger.getLogger(University_Page.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(University_Page.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_WebsiteMouseClicked

    private void WebsiteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WebsiteMouseEntered
        Website.setForeground(Color.RED.darker());
    }//GEN-LAST:event_WebsiteMouseEntered

    private void WebsiteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WebsiteMouseExited
        Website.setForeground(Color.GREEN.darker());
    }//GEN-LAST:event_WebsiteMouseExited

    private void BachelorExpensesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BachelorExpensesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BachelorExpensesActionPerformed

    private void CourseListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CourseListMouseClicked
        String s = CourseList.getSelectedValue();
        CourseCls ob = new CourseCls(str, s, cls);
        ob.setVisible(true);
        cls.dispose();
    }//GEN-LAST:event_CourseListMouseClicked

    private void CourseListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_CourseListValueChanged

    }//GEN-LAST:event_CourseListValueChanged

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        callcls.setVisible(true);
        cls.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private test.PanelRound AboutPanel;
    private javax.swing.JScrollPane AboutScroll;
    private javax.swing.JTextArea AboutText;
    private javax.swing.JTextArea Addressfield;
    private test.PanelRound AdmissionPanel;
    private javax.swing.JTextField Applicationfee;
    private javax.swing.JTextField BachelorExpenses;
    private test.PanelRound ContactPanel;
    private javax.swing.JScrollPane ContactScroll;
    private test.PanelRound CostPanel;
    private javax.swing.JLabel Country;
    private javax.swing.JList<String> CourseList;
    private test.PanelRound CoursePanel;
    private javax.swing.JScrollPane CourseScroll;
    private javax.swing.JTextField Emailfield;
    private javax.swing.JLabel Established;
    private javax.swing.JTextField Fbfield;
    private javax.swing.JLabel Name;
    private javax.swing.JTextField OnCampusExpenses;
    private javax.swing.JLabel Photo;
    private test.PanelRound PhotoPanel;
    private test.PanelRound RankingPanel;
    private javax.swing.JTextArea Rankingfield;
    private javax.swing.JTextField TutionfeeField;
    private javax.swing.JPanel UniName;
    private javax.swing.JLabel Website;
    private main.ImageAvatar imageAvatar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
