/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package udream;

import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Asus
 */
public class update_study_guide_jpanel extends javax.swing.JPanel {

    /**
    
     */
     JFrame frame;
    byte[] photo = null;
    byte[] photo2 = null;
    byte[] img = null;
    byte[] img1 = null;
    String filename;
    String filename2;
    int i=0,j=0;
    public update_study_guide_jpanel() {
        initComponents();

        
    }
    public update_study_guide_jpanel(JFrame frame) {
        initComponents();
        this.frame=frame;
        update_combobox();
         AutoCompleteDecorator.decorate(jComboBox1);
        jComboBox1.setSelectedIndex(-1);
        jTextArea1.setText(null);
        jTextField1.setText(null);
        jTextField2.setText(null);
        jTextField3.setText(null);
        jTextField4.setText(null);
        jTextField5.setText(null);
        jTextField6.setText(null);
        jTextField7.setText(null);
        jTextField8.setText(null);
        jTextField9.setText(null);
        jTextField10.setText(null);
        jTextField11.setText(null);
        jTextField12.setText(null);
        jTextField13.setText(null);
        jTextArea2.setText(null);
    }
    JFrame callcls;
      public update_study_guide_jpanel(JFrame frame,JFrame f) {
        initComponents();
        this.frame=frame;
        callcls=f;
        update_combobox();
         AutoCompleteDecorator.decorate(jComboBox1);
        jComboBox1.setSelectedIndex(-1);
        jTextArea1.setText(null);
        jTextField1.setText(null);
        jTextField2.setText(null);
        jTextField3.setText(null);
        jTextField4.setText(null);
        jTextField5.setText(null);
        jTextField6.setText(null);
        jTextField7.setText(null);
        jTextField8.setText(null);
        jTextField9.setText(null);
        jTextField10.setText(null);
        jTextField11.setText(null);
        jTextField12.setText(null);
        jTextField13.setText(null);
        jTextArea2.setText(null);
    }
         public void update_combobox(){
    try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/project", "root", "16ani");
            String sql = "SELECT country_name FROM project.study_destination ";
            
            PreparedStatement st = con.prepareStatement(sql);
            ResultSet rs = st.executeQuery();
            while (rs.next()) {
                jComboBox1.addItem(rs.getString("country_name"));
            }
        } catch (Exception e) {
            System.out.println("DDD");
        }
           }
         
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Country name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 29, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Overview");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 129, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Language of instruction");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 220, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Average cost to study");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 280, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Average cost of living");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 342, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Source of funding");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 401, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Exam required");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 449, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Intakes");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 504, -1, -1));

        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 25, 412, -1));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 220, 412, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 87, 412, -1));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 277, 412, -1));
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 339, 412, -1));

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 398, 412, -1));
        add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 446, 412, -1));
        add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 501, 412, -1));
        add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 560, 412, -1));

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 620, 412, -1));
        add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 680, 412, -1));

        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 740, 412, -1));
        add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 790, 412, -1));
        add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 840, 412, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Types of visa");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Types of Degree");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 630, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Credit system undergraduate per course");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 680, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Average total credit in undergraduate");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 740, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Credit system graduate per course");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 790, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("total credit in graduate degree");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 850, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("GPA scale");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 910, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("Flag");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 1020, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("Picture");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 1140, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("Admission process");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 1290, -1, -1));
        add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 900, 410, -1));

        jLabel19.setBackground(new java.awt.Color(153, 204, 255));
        jLabel19.setOpaque(true);
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 946, 290, 130));

        jLabel20.setBackground(new java.awt.Color(153, 204, 255));
        jLabel20.setOpaque(true);
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 1110, 330, 130));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 1260, 380, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("ATTACH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 1010, -1, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("ATTACH");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 1110, -1, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setText("NEXT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 1450, -1, -1));

        jButton4.setText("Go Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 1450, 90, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String coun_name=(String)jComboBox1.getSelectedItem();
        //System.out.println(coun_name);
        String lan=jTextField1.getText();
        String cost_study=jTextField2.getText();
        String cost_living=jTextField3.getText();
        String source_fun=jTextField4.getText();
        String exam=jTextField5.getText();
        String intake=jTextField6.getText();
        String type_visa=jTextField7.getText();
        String type_degree=jTextField8.getText();
        String overview=jTextArea1.getText();
        String under_per_course=jTextField9.getText();
        String under_total=jTextField10.getText();
        String gra_per_course=jTextField11.getText();
        String gra_total=jTextField12.getText();
        String gpa=jTextField13.getText();
        String adm_process=jTextArea2.getText();
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/project", "root", "16ani");
            String sql = "update project.study_destination set Language_Of_Instruction=?,AverageCostToStudy=?,AverageCostOfLiving=?,SourcesOfFunding=?,ExamsRequired=?,Intakes=?,TypesOfVisa=?,TypesOfDegrees=? where country_name=?";
            PreparedStatement st = con.prepareStatement(sql);
            st.setString(1,lan);
            st.setString(2,cost_study);
            st.setString(3, cost_living);
            st.setString(4,source_fun);
            st.setString(5,exam);
            st.setString(6,intake);
            st.setString(7,type_visa);
            st.setString(8,type_degree);
            st.setString(9,coun_name);
            st.executeUpdate();
            String sql1 = "update project.study_guide_main_table set overview=?,credit_undergraduate_per_course=?,credit_undergraduate_total=?,credit_graduate_per_course=?,credit_graduate_total=?,gpa_scale=?,admission_process=?,flag=?,picture=? where country_name=?";
            PreparedStatement st1 = con.prepareStatement(sql1);
            st1.setString(1,overview);
            st1.setString(2, under_per_course);
            st1.setString(3, under_total);
            st1.setString(4, gra_per_course);
            st1.setString(5, gra_total);
            st1.setString(6, gpa);
            st1.setString(7, adm_process);
           if(i==1)
           {
            st1.setBytes(8, photo);
           }
           else
           {
               st1.setBytes(8, img);
           }
           if(j==1)
           {
               st1.setBytes(9, photo2);
           }
           else
           {
               st1.setBytes(9, img1);
           }
           st1.setString(10, coun_name);
            st1.executeUpdate();
            JOptionPane.showMessageDialog(null, "update Successful");
             Study_guide_degree_table ob=new  Study_guide_degree_table(coun_name);
            ob.setVisible(true);
            frame.dispose();

        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, "update not Successful");
        }
         
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        jLabel19.setIcon(new ImageIcon(f.toString()));
        filename = f.getAbsolutePath();
        try {
            File img = new File(filename);
            FileInputStream fis = new FileInputStream(img);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buf = new byte[1024];
            for (int readNum; (readNum = fis.read(buf)) != -1;) {
                bos.write(buf, 0, readNum);
                i=1;
            }
            photo = bos.toByteArray();
        } catch (Exception e) {

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        jLabel20.setIcon(new ImageIcon(f.toString()));
        filename2 = f.getAbsolutePath();
        try {
            File img = new File(filename);
            FileInputStream fis = new FileInputStream(img);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buf = new byte[1024];
            for (int readNum; (readNum = fis.read(buf)) != -1;) {
                bos.write(buf, 0, readNum);
                j=1;
            }
            photo2 = bos.toByteArray();
        } catch (Exception e) {

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        String item = (String) jComboBox1.getSelectedItem();

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/project", "root", "16ani");
            String sql = "SELECT * FROM project.study_destination where country_name = '" + item + "'";
            PreparedStatement st = con.prepareStatement(sql);
            ResultSet rs = st.executeQuery();
            if (rs.next()) {
                jTextField1.setText(rs.getString("Language_Of_Instruction"));
                jTextField2.setText(rs.getString("AverageCostToStudy"));
                jTextField3.setText(rs.getString("AverageCostOfLiving"));
                jTextField4.setText(rs.getString("SourcesOfFunding"));
                jTextField5.setText(rs.getString("ExamsRequired"));
                jTextField6.setText(rs.getString("Intakes"));
                jTextField7.setText(rs.getString("TypesOfVisa"));
                jTextField8.setText(rs.getString("TypesOfDegrees"));
            }
                
                
            
        } catch (Exception e) {

        }
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/project", "root", "16ani");
            String sql = "SELECT * FROM project.study_guide_main_table where country_name = '" + item + "'";
            PreparedStatement st = con.prepareStatement(sql);
            ResultSet rs = st.executeQuery();
            if(rs.next())
            {
                jTextArea1.setText(rs.getString("overview"));
                jTextField9.setText(rs.getString("credit_undergraduate_per_course"));
                jTextField10.setText(rs.getString("credit_undergraduate_total"));
                jTextField11.setText(rs.getString("credit_graduate_per_course"));
                jTextField12.setText(rs.getString("credit_graduate_total"));
                jTextField13.setText(rs.getString("gpa_scale"));
                jTextArea2.setText(rs.getString("admission_process"));
                img = rs.getBytes("flag");
                ImageIcon image = new ImageIcon(img);
                Image im = image.getImage();
                Image myImg = im.getScaledInstance(jLabel19.getWidth(), jLabel19.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon newImage = new ImageIcon(myImg);
                jLabel19.setIcon(newImage);
                
                img1 = rs.getBytes("picture");
                
                ImageIcon image1 = new ImageIcon(img1);
                Image im1 = image1.getImage();
                Image myImg1 = im1.getScaledInstance(jLabel20.getWidth(), jLabel20.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon newImage1 = new ImageIcon(myImg1);
                jLabel20.setIcon(newImage1);
                
            }
        }
        catch (Exception e) {

        }
        
        
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        callcls.setVisible(true);
        frame.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
